- name: Download and build libopus  
  run: |  
    wget https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz  
    tar xf opus-1.3.1.tar.gz  
    cd opus-1.3.1  
    ./configure \  
      --enable-static --disable-shared \  
      --disable-doc --disable-extra-programs \  
      --prefix="$HOME/opus-prefix" \  
      LDFLAGS="-lm"  
    make -j$(nproc)  
    make install
